version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.10
      - image: postgres:9.6
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: llegarafindemes
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
            name: chmod permissions
            command: chmod +x ./gradlew
      - run: gradle dependencies
      - run: ./gradlew jacocoTestReport
      - store_artifacts:
          path: build/reports/jacoco/test/jacocoTestReport.xml